name: jashn_e_fabric
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.2.1
  font_awesome_flutter: ^10.6.0
  google_fonts: ^6.1.0
  flutter_staggered_grid_view: ^0.7.0
  responsive_framework: ^1.1.1
  flutter_animate: ^4.2.0
  transparent_image: ^2.0.1  # For placeholder loading
  shimmer: ^3.0.0  # For loading animations
  cached_network_image: ^3.3.0  # For caching network images
  animations: ^2.0.8  # For pre-built animations
  spring: ^2.0.2  # For spring-based animations

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/images/carousel/

